@startuml
package rest{
    class GreetingsStatsJson <<Record>> {
        - counters : Map<String, Long>
    }
}
package domain{
    class GreetingsStats <<entity>> {
        - counters : Map<String, Long>
        + getStatsFor(String type) : Optional<Long>
        + increaseCounterFor(String type) : GreetingsStats
    }
}
package persistence{
    class Counter{
        - id : long
        - name : String
        - count : long
    }
}
@enduml