'Doc : https://github.com/plantuml-stdlib/C4-PlantUML
@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

HIDE_STEREOTYPE()

!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.3.0
!includeurl ICONURL/common.puml
!include ICONURL/devicons/java.puml
!include ICONURL/devicons/postgresql.puml
!include ICONURL/devicons2/apache_line.puml
!include ICONURL/font-awesome-5/user_tie.puml

Person(user,"User",$sprite="user_tie")
'System_Boundary(sys,"Greetings Messages"){
    Container(greetings, "greetings-service","Create Greetings Messages", $sprite="java")
    ContainerDb(greetings_db,"Greetings DB","PostgreSQL",$sprite="postgresql")
    Container(stats, "greetings-stats-service","Records Statistics", $sprite="java")
    ContainerDb(stats_db,"Statistics DB","PostgreSQL",$sprite="postgresql")
    ContainerQueue(kafka,"Kafka","greeting_topic",$sprite="apache_line")
'}

Rel(greetings, greetings_db, "Reads/Writes")
Rel(stats, stats_db, "Reads/Writes")
Rel_D(greetings, kafka, "Produces Events")
Rel_D(stats, kafka, "Consumes Events")
Rel_L(stats, greetings, "GET /greetings/{identifier}", "HTTP")
Rel_D(user,greetings,"POST /greetings", "HTTP")
Rel_D(user,stats,"GET /stats", "HTTP")
@enduml