'Doc : https://github.com/plantuml-stdlib/C4-PlantUML
@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

HIDE_STEREOTYPE()

!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master
!include ICONURL/common.puml
!include ICONURL/devicons/angular.puml
!include ICONURL/devicons/java.puml
!include ICONURL/devicons/postgresql.puml
!include ICONURL/devicons2/apache_line.puml
!include ICONURL/font-awesome-5/user_tie.puml

Person(user,"User",$sprite="user_tie")
'System_Boundary(sys,"Greetings Messages"){
    Container(greetings_ui,"greetings-ui","Greetings User Interface", $sprite="angular")
    Container(greetings, "greetings-service","Create Greetings Messages", $sprite="java")
    ContainerDb(greetings_db,"Greetings DB","PostgreSQL",$sprite="postgresql")
    Container(stats, "greetings-stats-service","Records Statistics", $sprite="java")
    ContainerDb(stats_db,"Statistics DB","PostgreSQL",$sprite="postgresql")
    ContainerQueue(kafka,"Kafka","greeting_topic",$sprite="apache_line")
'}

Rel(greetings_ui, greetings, "GET|POST|PUT /greetings/*", "HTTP")
Rel(greetings_ui, stats, "GET /stats", "HTTP")
Rel(greetings, greetings_db, "Reads/Writes")
Rel(stats, stats_db, "Reads/Writes")
Rel_D(greetings, kafka, "Produces Events", "Async")
Rel_D(stats, kafka, "Consumes Events","Async")
Rel_L(stats, greetings, "GET /greetings/{identifier}", "HTTP")
Rel_D(user,greetings_ui,"User Interface")
@enduml