name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install UI dependencies
        working-directory: ./greetings-ui
        run: yarn install

      - name: Install E2E dependencies
        working-directory: ./greeting-ui-e2e
        run: yarn install

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./greeting-ui-e2e
          start: yarn test
          wait-on: 'http://localhost:5173'
          wait-on-timeout: 120
          browser: chrome
          record: false

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: ./greeting-ui-e2e/cypress/screenshots
          if-no-files-found: ignore